version: 2.1
 jobs:
   build:
     docker:
       - image: "circleci/node:<< pipeline.parameters.image-tag >>"
         auth:
           username: mydockerhub-user
           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
     environment:
       IMAGETAG: "<< pipeline.parameters.image-tag >>"
     steps:
       - run: echo "Image tag used was ${IMAGETAG}"
 parameters:
   image-tag:
     default: latest
     type: string
